name: MessageExamples
version: 1.0.0
description: Paper Message API examples.
# Comments
author: Engineeringcode
website: https://www.engineeringcode.net/

main: net.engineeringcode.mc.MessageExamples
api-version: 1.15

commands:

permissions:
